### ISSUE TITLE
icons are not sized properly

### ISSUE THREAD

**Issue by jelkosz** [mareklibra/userportal#10]
in vms.css the .card-pf-icon contains:

    height: 100%;
    overflow: hidden;
    display: block;
    height: 106px;
    margin: 0 auto;
    width: 106px;

The problem is that both the width and height are set making the os icons look ugly. Better would be to use only:

    overflow: hidden;
    display: block;
    height: 106px;
    margin: 0 auto;

**Comment by mareklibra** [comment]
Fixed by 02e457f41258676fdc120e40c4ae90d35282edcb
