### ISSUE TITLE
Rename to something more generic

### ISSUE THREAD

**Issue by jelkosz** [mareklibra/userportal#20]
Currently this project is called "userportal", but there is a chance that it will grow to something much bigger than just a simple user portal. For this reason I would propose to rename the project to some generic name not connected to oVirt nor to fact it is currently a userportal.
Some proposals which came to my mind:

1: Boudica: an ancient Celtic warrior princess which unified bunch of Celtic tribes and was leading them to a large scale uprising against Romans.
2: Salome: always nicely pretentious to use biblical names :) I like the sound of this name and also the fact that she was a beautiful dancer (among other things) which fits well to a frontend which should be nice and has nice smooth movements (transitions).
3: Karpaty or Carpaty: large beautiful mountains connecting couple of states in central Europe. Points also to the origins of the tool :)

What do you think? My slight preference is 1.

**Comment by mareklibra** [comment]
"Web UI" sounds nice :-)
