### ISSUE TITLE
add a visual indication that an action has been performed

### ISSUE THREAD

**Issue by jelkosz** [mareklibra/userportal#26]
The following scenario:
- have a down VM
- click start
- hmmmm, did I click it or not? Nothing happened.

It would be good to have an immediate visual indication that I actually did.

**Comment by mareklibra** [comment]
Recently on review:
- gray-out the action once it's issued
- switch to normal if it fails (so reissue is possible)
- keep gray if REST API call succeeds (no reason to reissue, rerender after scheduled refresh)

For completeness, the refresh is not yet implemented but is planed to be.

To try:
- https://github.com/mareklibra/userportal/pull/28
- https://github.com/matobet/ovirt-ui-components/pull/8
