### ISSUE TITLE
password logged when the connection is not successful

### ISSUE THREAD

**Issue by jelkosz** [mareklibra/userportal#46]
For example, if you set the package.json to have incorrect proxy and try to login, the error message in logs contains the cleartext password:

The 'vms' reducer action={"type":"FAILED_EXTERNAL_ACTION","payload":{"message":"Internal Server Error","shortMessage":"LOGIN failed","type":500,"action":{"type":"LOGIN","payload":{"credentials":{"username":"admin@internal","password":"the password"}}}}}

**Comment by mareklibra** [comment]
Fixed
