### ISSUE TITLE
Use compression by default

### ISSUE THREAD

**Issue by mykaul** [mareklibra/userportal#58]
We have switched to using Compression on by default in the oVirt SDK. I can only assume that enabling it in the JS code here might have a chance to improve performance - especially over WAN.

**Comment by jelkosz** [comment]
@mykaul it should be enabled and last time I have tried it was using compression. Did you see some issues with this?

**Comment by mykaul** [comment]
No, if it's enabled - all good. (perhaps I've missed where it is enabled). Closing.
