### ISSUE TITLE
VM detail hidden when there are lots of VMs

### ISSUE THREAD

**Issue by jelkosz** [mareklibra/userportal#8]
If there are many VMs, scroll down and pick some VM from the bottom.
The result is that the VM detail is rendered on the top of the page invisible for the user. To see the VM detail, you need to scroll up. (took me some time to find out it is rendered there and it did not fail to render it ;) )

**Comment by mareklibra** [comment]
5e10a82cbda868572fee29d6623359c824b4d67c
